#ifndef IRONBOY_MOTION
#define IRONBOY_MOTION

#define MOTION_WALKFORWARD            100
#define MOTION_TURN_LEFT              101
#define MOTION_TURN_RIGHT             102
#define MOTION_SIDE_STEP_LEFT         104
#define MOTION_SIDE_STEP_RIGHT        105
#define MOTION_STAND                  106
#define MOTION_SIT_DOWN               107
#define MOTION_GET_UP_FORWARD         108
#define MOTION_GET_UP_BACKWARD        109
#define MOTION_BODY_SIDE_TILT         110
#define MOTION_PROVOKE                111
#define MOTION_PUSHUP                 112
#define MOTION_SIDE_KICK_LEFT         113
#define MOTION_SIDE_KICK_RIGHT        114
#define MOTION_CELEBRATE_VICTORY      115
#define MOTION_BOW_DOWN               116
#define MOTION_ARM_WHIRL              117
#define MOTION_CLAP                   118
#define MOTION_GREET_WAVE             119
#define MOTION_WING_FLAP_LEFT         120
#define MOTION_WING_FLAP_RIGHT        121
#define MOTION_SIDE_TRUMBLING_LEFT    122
#define MOTION_SIDE_TRUMBLING_RIGHT   123
#define MOTION_FRONT_PUNCH            124
#define MOTION_SIDE_PUNCH_LEFT        125
#define MOTION_SIDE_PUNCH_RIGHT       126
#define MOTION_REAR_ATTACK            127
#define MOTION_ONE_STEP_FORWARD       128
#define MOTION_ONE_STEP_BACKWARD      129
#define MOTION_STEP_FWD_PUNCH         130
#define MOTION_FRONT_TUMBLING         131
#define MOTION_BACK_TUMBLING          132
#define MOTION_ARM_WAVE               133
#define MOTION_BUTTERFLY              134
#define MOTION_SIDE_MOVE_PUNCH_LEFT   135
#define MOTION_SIDE_MOVE_PUNCH_RIGHT  136
#define MOTION_LARGE_STEP_TURN_LEFT   137
#define MOTION_LARGE_STEP_TURN_RIGHT  138
#define MOTION_FRONT_LIFT_ATTACK      139
#define MOTION_SIDE_LIFT_ATTACK_LEFT  140
#define MOTION_SIDE_LIFT_ATTACK_RIGHT 141
#define MOTION_BACK_DROP_ATTACK       142
#define MOTION_SIT_SIDE_MOVE_LEFT     143
#define MOTION_SIT_SIDE_MOVE_RIGHT    144
#define MOTION_SIT_FRONT_ATTACK       145
#define MOTION_SIT_SIDE_ATTACK_LEFT   146
#define MOTION_SIT_SIDE_ATTACK_RIGHT  147
#define MOTION_SIT_AROUND_ATTACK      148
#define MOTION_STOMPING_MOVE_FORWARD  149
#define MOTION_STOMPING_TURN_LEFT     150
#define MOTION_STOMPING_TURN_RIGHT    151
#define MOTION_STOMPING_MOVE_BACKWARD 152
#define MOTION_BALL_TACKLE_FRONT      153
#define MOTION_BALL_FRONT_KICK_LEFT   154
#define MOTION_BALL_FRONT_KICK_RIGHT  155
#define MOTION_BALL_HEEL_KICK         156
#define MOTION_BALL_SIDE_KICK_LEFT    157
#define MOTION_BALL_SIDE_KICK_RIGHT   158
#define MOTION_STOMPING_MOVE_ATTACK   159
#define MOTION_JUMP                   160
#define MOTION_LIE_FACE_DOWN          161
#define MOTION_LIE_FACE_UP            162
#define MOTION_HOLD_TOPPLE_ATTACK_LEFT  163
#define MOTION_HOLD_TOPPLE_ATTACK_RIGHT 164
#define MOTION_RISE_UP_FROM_FACE_DOWN   165
#define MOTION_CRAWL_FORWARD          166
#define MOTION_CRAWL_SIDE_LEFT        167
#define MOTION_CRAWL_SIDE_RIGHT       168
#define MOTION_CRAWL_BACKWARD         169
#define MOTION_CRAWL_RISE_UP          170
#define MOTION_KEEPER_STANCE          171
#define MOTION_KEEPER_FRONT_BLOCK     172
#define MOTION_KEEPER_SIDE_BLOCK_LEFT 173
#define MOTION_KEEPER_SIDE_BLOCK_RIGHT  174
#define MOTION_KEEPER_BALL_KICK       175
#define MOTION_KEEPER_LOW_BLOCK       176
#define MOTION_BREATHE_ACTION         177
#define MOTION_ONE_LEG_SQUAT_LEFT     178
#define MOTION_ONE_LEG_SQUAT_RIGHT    179
#define MOTION_DANCE_KPOP_1           180 
#define MOTION_DANCE_KPOP_2           181
#define MOTION_DANCE_KPOP_3           182
#define MOTION_DANCE_KPOP_4           183
#define MOTION_DANCE_KPOP_5           184
#define MOTION_DANCE_KPOP_6           185
#define MOTION_DANCE_KPOP_7           186
#define MOTION_DANCE_KPOP_8           187
#define MOTION_DANCE_KPOP_9           188
#define MOTION_HEART                  189
#define MOTION_TIPTOE_MOVE_FORWARD    190
#define MOTION_TIPTOE_TURN_LEFT       191
#define MOTION_TIPTOE_TURN_RIGHT      192
#define MOTION_TIPTOE_MOVE_BACKWARD   193
#define MOTION_FLYING_STAND_UP        194
#define MOTION_LARGE_SIDE_STEP_LEFT   195
#define MOTION_LARGE_SIDE_STEP_RIGHT  196
#define MOTION_FLYING_SIT_DOWN        197
#define MOTION_LARGE_STEP_FORWARD     198
#define MOTION_LARGE_STEP_BACKWARD    199

#endif






